kind: Deployment
metadata:
  name: nginx
  namespace: minikube-nginx-kadet
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1:15.8
          ports:
            - containerPort: 80
